- name: Setup Raspberry Pi
  hosts: myhosts
  become: true

  tasks:
    - name: Update en upgrade apt-pakketten
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installeer build-essential tools
      apt:
        name: build-essential
        state: present

    - name: Installeer Node.js en npm
      apt:
        name:
          - nodejs
          - npm
        state: present
  
    - name: Installeer Node-RED via npm
      npm:
        name: node-red
        global: yes

    - name: Maak systemd service bestand voor Node-RED
      copy:
        dest: /etc/systemd/system/nodered.service
        content: |
          [Unit]
          Description=Node-RED
          After=network.target

          [Service]
          ExecStart=/usr/bin/env node-red --userDir /home/tsml/.node-red
          WorkingDirectory=/home/tsml
          User=tsml
          Group=tsml
          Environment="NODE_OPTIONS=--max-old-space-size=128"
          Nice=10
          SyslogIdentifier=Node-RED
          StandardOutput=syslog
          Restart=on-failure
          PermissionsStartOnly=true

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd daemon
        - Restart Node-RED Service

    - name: Installeer Python en pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

  handlers:
    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Restart Node-RED Service
      systemd:
        name: nodered
        state: restarted
        enabled: yes
